DisplayLink/evdi

module/evdi_encoder.c
module/evdi_modeset.c

This is an initial fix for the Linux 4.5 incompatibility. I am still in the process of testing if it fixed the problem with DisplayLink not showing the display, but this will fix the installation errors at least.
Feel free to offer suggestions or comments, this is my first kernel driver PR.

Modifying for Linux 4.5 compatibility

---

library/Makefile

The Makefile for the library does not contain an Include Directory. Thus, you cannot make the library on its own, which is bad when creating packages for distributions.
```
library $ make
cc -std=gnu99 -fPIC    -c -o evdi_lib.o evdi_lib.c
evdi_lib.c:8:22: fatal error: evdi_drm.h: No such file or directory
#include "evdi_drm.h"
^
compilation terminated.
<builtin>: recipe for target 'evdi_lib.o' failed
```
With this pull request you can just "make" the library:
```
library $ make
cc -I../module -std=gnu99 -fPIC    -c -o evdi_lib.o evdi_lib.c
cc evdi_lib.o -o libevdi.so -lc -lgcc -shared
```
This is already changed in the Makefile in the main directory as it containts:
```
CFLAGS="-I../module $(CFLAGS)" $(MAKE) -C library $(MFLAGS)
```

Add Include Directory for library

---

module/evdi_modeset.c

/tmp/evdi/module/evdi_modeset.c: In function ‘evdi_crtc_cursor_move’:
/tmp/evdi/module/evdi_modeset.c:250:2: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
if (!evdi_cursor_enabled(evdi->cursor))
^~
/tmp/evdi/module/evdi_modeset.c:252:3: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
ret = evdi_cursor_move(crtc, x, y, evdi->cursor);
^~~

Fix misleading indentation

---

library/evdi_lib.c

Clang wants all members of a struct to be initialized. It issues the
following warnings on the code, before the fix
evdi_lib.c:307:37: error: missing field 'dev_index' initializer
[-Werror,-Wmissing-field-initializers]
struct drm_evdi_connect cmd = { 0 };
^
evdi_lib.c:313:55: error: missing field 'y1' initializer
[-Werror,-Wmissing-field-initializers]
struct drm_clip_rect kernelDirts[MAX_DIRTS] = { { 0 } };
^

Fix missing struct initializers reported by clang

---

module/evdi_connector.c

Since this commit:
commit 0993f1d0d8a1b516df4a059605af9979049d0187
Author: Damien Lespiau <damien.lespiau@intel.com>
Date:   Thu Nov 28 15:29:17 2013 +0000
drm: Make the connector mode_valid() vfunc return a drm_mode_status enum
To make it clear what exactly mode_valid() should return.
Signed-off-by: Damien Lespiau <damien.lespiau@intel.com>
Signed-off-by: Daniel Vetter <daniel.vetter@ffwll.ch>
upstream has returned enum drm_mode_status instead of int.  Functionally it shouldn't change anything as you're already returning stuff from that enum, and those enum values go back to at least 2008, so it should be a perfectly compatible change to make.  
This patch comes from the grsecurity project, and it will fix compatibility with RAP and other fine-grained kernel CFI methods.

Fix return value of evdi_mode_valid

---

.travis.yml

Testing with the current development version of the linux kernel should cause unexpected errors and to have compatibility issues before it's released in the wild.
It's interesting to build with it, but it shouldn't make the builds break.

Ignore master kernel version faiures

---

module/dkms.conf

`KERNELRELEASE` is automatically appended only to `MAKE` command, but not `CLEAN`, see http://manpages.ubuntu.com/manpages/trusty/man8/dkms.8.html .
At last on Fedora 27, the result is as follows:
```
Building module:
make clean KVERSION=4.14.16-300.fc27.x86_64 DKMS_BUILD=1
/lib/modules//build
make KBUILD_VERBOSE=1 SUBDIRS=/var/lib/dkms/evdi/1.0.0/build SRCROOT=/var/lib/dkms/evdi/1.0.0/build -C /lib/modules//build clean
make[1]: *** /lib/modules//build: No such file or directory.  Stop.
make: *** [Makefile:26: clean] Error 2
(bad exit status: 2)
(...)
```
Resulting in non-zero exit code of dkms command.

added KERNELRELEASE variable to CLEAN in dkms.conf

---

.travis.yml

ccache is a compiler cache. It speeds up recompilation by caching previous compilations and detecting when the same compilation is being done again.
Travis supports caching compilation of C/C++/Obj C projects using ccache.
This PR enables that cache.

Use ccache for faster builds

---

module/evdi_drv.c

Patch to prevent DMAR domain allocation failure copied from https://patchwork.kernel.org/patch/10778139/
Tested and working on Intel i7, Gentoo, kernel 4.19.23, xorg-server-1.20.4

Prevent IOMMU domain allocation failure

---

module/evdi_fb.c

Linux commit 168b85e9b223 ("drm/fb-helper: Unexport fill_{var,info}")
unexported drm_fb_helper_fill_fix and drm_fb_helper_fill_var, so
now use the new helper drm_fb_helper_fill_info instead.
Signed-off-by: Colin Ian King <colin.king@canonical.com>

Linux 5.2: use drm_fb_helper_fill_info

---

module/evdi_cursor.c
module/evdi_fb.c
module/evdi_painter.c

When userspace calls add_fb2 ioctl, part of that is the offsets array. EVDI has
been assuming that the offsets are zero by not using them at all. If userspace
uses non-zero offset, that leads to incorrect buffer contents beings accessed.
Honour the offsets set by userspace. Only offsets[0] is used, because EVDI does
not support multi-plane formats.

Use FB offsets

---

Makefile
module/evdi_connector.c
module/evdi_fb.c
module/evdi_ioc32.c
module/evdi_main.c
module/evdi_painter.c

Added an additional flag EL8.1 which handles the logic for Enterprise Linux versions from 8.1 onward. 8.0 does not require this flag.

Added support for EL8.1+

---

.travis.yml

Since there are some issues with linux 5.8 and the current version of EVDI, it seems appropriate to include the latest kernels to CI

include CI builds for linux 5.7 and 5.8

---

.travis.yml
module/evdi_cursor.c
module/evdi_drv.c
module/evdi_fb.c
module/evdi_gem.c
module/evdi_modeset.c

Please note I do not have any HW to test these changes.

Adjust to kernel 5.9

---

ci/run_style_check

Closes #231 
Download the scripts run in `ci/run_style_check` from the latest supported kernel version instead of the mainline tree.

Use CI scripts from the latest supported kernel version

---

module/evdi_gem.c

Thank you @abucodonosor!
Fixes https://github.com/DisplayLink/evdi/issues/234 courtesy of @abucodonosor.
Confirmed ~~support~~ build for DisplayLink Devel 1.8 on Kernel 5.10.0-rc6-1
~~Not only does it build, but evdi 1.8 is working!~~
Not only does it build, but evdi 1.7 is working!
CC: @bnavigator
```
cat: /etc/redhat-release: No such file or directory
CFLAGS="-Werror -Wextra -Wall -Wmissing-prototypes -Wstrict-prototypes -Wno-error=missing-field-initializers" make -C module 
make[1]: Entering directory './evdi/module'
make -C /lib/modules/5.10.0-rc6-1-git/build M=$PWD
make[2]: Entering directory '/usr/lib/modules/5.10.0-rc6-1-git/build'
CC [M]  ./evdi/module/evdi_drv.o
CC [M]  ./evdi/module/evdi_modeset.o
CC [M]  ./evdi/module/evdi_connector.o
CC [M]  ./evdi/module/evdi_encoder.o
CC [M] …
```

Added support for 5.10 by applying @abucodonosor's patch found in #234.

---

library/Makefile
library/evdi_lib.h
module/Makefile
module/dkms.conf
module/evdi_drv.h

This patch adjusts the build for the new release version of
evdi to version 1.7.2.

Adjust build for version 1.7.2 release

---

docs/details.md
docs/quickstart.md

This clarifies when to handle events, which confused me until I got help (#265), and that you need to handle events promptly and request updates, and grab pixels regularly or your display may freeze.
As far as I can tell, it is possible to write a program that uses evdi and doesn't require administrator permissions without too much difficulty (either have a helper with admin rights add devices, or ensure devices are added on module load). I document that as well.
Closes #268

Clarify what needs admin rights and how to handle events in the docs

---

module/evdi_gem.c
module/evdi_params.c
module/evdi_params.h

DisplayLink screen is unusable when connected to an AMD system due to a very slow refresh rate. 
**Configuration:**
- Dock: 17e9:6008 DisplayLink Targus USB3 DV4K DOCK w PD100W
- APU: AMD Ryzen 7 PRO 4750U with Radeon Graphics
- 4K screen connected to the Targus dock.
- Debian/Bullseye/Kernel 5.10.0-6-amd64, standard amdgpu opensource driver with Gnome 3.38.4
**Analysis**
Slow screen refresh rate seems to be related to a very slow texture copy in the EVDI module. This can be measured using bpftrace. The output shows that all copies take around 120ms (4K screen), which explains observable slow refresh rate.
`bpftrace -e 'kprobe:evdi_painter_grabpix_ioctl { @beg = nsecs; } kretprobe:evdi_painter_grabpix_ioctl { $end = nsecs; @["frame_copy_ms"] = lhist(($end - @beg)/1000000, 1, 200, 1);}' …

add an option to disable fast path texture import, work-around for slow AMD copy (gnome/wayland)

---

module/evdi_cursor.c
module/evdi_drm_drv.c
module/evdi_fb.c
module/evdi_gem.c
module/evdi_modeset.c
module/evdi_params.c
module/evdi_platform_dev.c

This patch allows evdi to be compiled on RHEL 8.4 and its derivatives.
After running the `ci/run_style_check`, there were some fixes that needed to be made. That is included in this change.
Fixes #283

Fix Compile On RHEL 8.4 and Derivatives

---

module/evdi_modeset.c
module/evdi_painter.c

Hi DisplayLink, 
The hardware cursor is broken on Gnome 40++, hence the performance is not good. It looks like Gnome now requires the cursor to be passed via the cursor plane and not legacy API. This MR implements it.
Unfortunately it seems that the driver cannot advertise both APIs and let the compositor choose the one it wants (advertising both causes bug-check in DRM). I can see the need for a compile time switch between the two, but I do not know what rule I should implement (ideas?). 
Anyway, it works on Gnome 41 (Fedora 35), Gnome 40 (Debian/Bookworm) and Gnome 3.38 (Debian/Bullseye, this one actually works with the old and new API). I have not tested any Ubuntu variants. 
CI:
* Style-check - OK (unrelated warning) 
* Kernel builds: 5.X OK, master fails (unrelated).
Thanks.
Piotr

hardware cursor - switch to cursor planes

---

module/evdi_fb.c

Clang is stricter when reporting errors. In this case, when building
with CONFIG_FB unset, compiling with clang will produce the following
error:
evdi_fb.c:88:12: error: unused function 'evdi_handle_damage' [-Werror,-Wunused-function]
static int evdi_handle_damage(struct evdi_framebuffer *fb,
^
1 error generated.
Since evdi_handle_damage() is only used when CONFIG_FB is set, move the
`ifdef CONFIG_FB` to encapsulate the evdi_handle_damage() function.
Tested with copy of evdi imported into the chromeos-5.10 kernel.
Before submitting the PR please make sure you have run *ci* scripts:
* `./ci/build_against_kernel` (see `--help` for all options)
We need backward compatibility and this script is a handy way of testing
build compliance with many kernel versions.
* `./ci/run_style_check`
We want …

Fix compilation when building with clang

---

module/evdi_drm_drv.h
module/evdi_gem.c

Tested on 5.14, but it should fix it on 5.11-5.13 as well.
Seems that the `is_iomem` flag is set to `true` under nvidia blob drivers, causing the `BUG_ON(!dma_buf_map_is_equal(&dmabuf->vmap_ptr, map));` check in `dma_buf_vunmap` to trigger since `evdi_gem_vunmap` explicitly set it to `false`.
This should solve #288, #300, and #313.

Fix dma-buf crash on kernel 5.11+

---

module/evdi_gem.c

In particular, when software rendering, it is entirely possible to have
a dmabuf that did not come from an externally loaded kernel module. As a
result, the owner field is NULL, and checking the owner's name
segfaults.
Tested on the Asahi Linux kernel, where software rendering is used.

Fix crashes with dmabufs not from external kernel modules

---

module/evdi_platform_drv.c
module/evdi_sysfs.c

Allow to use evdi in systems with USB support disabled.
Signed-off-by: Andrea Righi <andrea.righi@canonical.com>

support USB-less systems

---

module/evdi_drm_drv.h
module/evdi_painter.c

Fixes https://github.com/DisplayLink/evdi/issues/376 by implementing @Crashdummyy's fix as posted [here](https://github.com/DisplayLink/evdi/issues/376#issuecomment-1237450695), +  fixes the style used in evdi_painter.c 
Before submitting the PR please make sure you have run *ci* scripts:
* `./ci/build_against_kernel` (see `--help` for all options) (done)
We need backward compatibility and this script is a handy way of testing
build compliance with many kernel versions.
* `./ci/run_style_check` (done)
We want to be as style compliant as possible. Again, this is a handy way of
checking it.
If you have more than one change consider creating separate PRs for them; it
will make the review process much easier. Also provide some description (links
to source code or mailing list are welcome - …

Add support for kernel 6.0 + a minor fix

---

module/evdi_encoder.c

When building against the 6.1.6 kernel (maybe others..) the name field in drm_encodeer_init() is checked as a printf format string.  This causes a fatal error:
2023/01/24 11:37:04 akmodsbuild: /tmp/akmodsbuild.N6DUGkQn/BUILD/evdi-bdc258b25df4d00f222fde0e3c5003bf88ef17b5/_kmod_build_6.1.6-100.fc36.x86_64/evdi_encoder.c:57:32: error: format not a string literal and no format arguments [-Werror=format-security]
2023/01/24 11:37:04 akmodsbuild: 57 |                                DRM_MODE_ENCODER_TMDS, dev_name(dev->dev));
2023/01/24 11:37:04 akmodsbuild: |                                ^~~~~~~~~~~~~~~~~~~~~
2023/01/24 11:37:04 akmodsbuild: cc1: some warnings being treated as errors
2023/01/24 11:37:04 akmodsbuild: make[1]: *** [scripts/Makefile.build:250: …

Use simple format string for name since printf args are checked now

---

module/evdi_drm_drv.c
module/evdi_fb.c

I am getting compile errors for Linux Kernel 6.6. See #433 and [NixOS/nixpkgs Issue 265868](https://github.com/NixOS/nixpkgs/issues/265868). This PR applies fixes that I think are correct based on the changes made to Linux Kernel 6.6.
Specifically, the changes made in this patch are
1. `drm_gem_prime_fd_to_handle` and `drm_gem_prime_handle_to_fd` are no longer exported as these are the defaults (if I understand correctly), so `.prime_fd_to_handle` and `.prime_handle_to_fd` no longer need to be set.
2. `FBINFO_DEFAULT` is no longer defined as it was defined as `0` and this is the default value (assuming the `info` struct is zero initialised)
I have done limited testing on my system and it seems to work and the CI build against Linux Kernel 6.6 passes.

Resolve compile errors for Linux Kernel 6.6

---

module/evdi_drm_drv.c
module/evdi_fb.c
module/evdi_gem.c
module/evdi_ioc32.c
module/evdi_modeset.c
module/evdi_painter.c

These kernels have DRM changes from kernel 6.3 backported to them. The specific enterprise linux versions are 9.3 and 8.9.

Adjusting compile to account for newer EL 8 and EL 9 kernels

---

module/evdi_debug.c
module/evdi_drm_drv.c
module/evdi_i2c.c

* Remove now obsolete Symbol [I2C_CLASS_DDC](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=ed8d84530ab0a3b7b370e8b28f12179314dcfcc3)
* Remove now obsolete Symbol [DRM_UNLOCKED](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=2798ffcc1d6a788b5769b1fbcf0750dfc06ae98a)
This should allow ( for now ) to compile against Kernel 6.8
Closes #448

Remove obsolete symbols to allow compilation against kernels >=6.8

---

module/evdi_fb.c

Added support for Kernels 6.1.51 and newer
This would mean support for Steam OS 3.5.19

Steam OS 3.5 Support (Kernel 6.1.51+)

---

module/evdi_drm_drv.c

This PR fixes the following issue: https://github.com/DisplayLink/evdi/issues/495
Tested on kernel 6.12 using latest Arch packages. Also tested against kernel 6.11.9 and latest TLS 6.6.63 for backwards compatibility.

Fix compilation error with kernel 6.12

---

module/README.md

Add usage instructions to aid those of us manually deploying and working with DisplayLink devices.

module: add README with instructions on usage

---

module/evdi_drm_drv.c
module/evdi_drm_drv.h
module/evdi_fb.c
module/evdi_gem.c
module/evdi_i2c.c
module/evdi_modeset.c
module/evdi_painter.c
module/evdi_platform_dev.c
module/evdi_platform_dev.h

This commit fixes building evdi on the latest EL9 kernels which have backported changes from the 6.11 kernel.
While going through the code, made some other adjustments for what applies to EL8 and what doesn't.

Fix building on latest EL9 kernels

---

module/evdi_gem.c
module/evdi_painter.c

The commit 3651b6debf631febf470106d43199d7fbd7bfd56 causes an issue for kernels prior to 6.13-rc3.

Fix building on kernels prior to 6.13
